[project]
name = "openai-api-agent-project"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "openai",
    "fastapi",
    "uvicorn",
    "python-multipart",
    "jinja2",
    "python-dotenv",
    "yfinance",
]
