[project]
name = "openai-agent"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "openai",
    "fastapi[standard]",
    "fastmcp",
    "yfinance",
    "python-dotenv",
    "pyyaml",
    "pytz",
]